#/bin/bash


cd ../hadoop-hdfs-project/hadoop-hdfs
mvn test -e -Dtest=TestMetaSave
#mvn test -e -Dtest=TestAclConfigFlag,TestAllowFormat,TestAuditLogger,TestAuditLogs,TestBlockUnderConstruction,TestCacheDirectives,TestCheckPointForSecurityTokens,TestClusterId,TestCreateEditsLog,TestDeadDatanode,TestDeduplicationMap,TestDefaultBlockPlacementPolicy,TestDeleteRace,TestEditLogAutoroll,TestEditLogFileInputStream,TestEditLogFileOutputStream,TestEditLogJournalFailures,TestEditsDoubleBuffer,TestFileContextAcl,TestFileLimit,TestFsck,TestFsckWithMultipleNameNodes,TestFSDirectory,TestFSImage,TestFSImageWithAcl,TestFSImageWithXAttr,TestFsLimits,TestFSNamesystemMBean,TestGenericJournalConf,TestGetBlockLocations,TestGetImageServlet,TestHDFSConcat,TestHostsFiles,TestINodeAttributeProvider,TestINodeFile,TestLargeDirectoryDelete,TestLeaseManager,TestListCorruptFileBlocks,TestMalformedURLs,TestMetadataVersionOutput,TestMetaSave,TestNameEditsConfigs,TestNameNodeHttpServer,TestNameNodeRecovery,TestNameNodeResourcePolicy,TestNameNodeRespectsBindHostKeys,TestNamenodeRetryCache,TestNameNodeRetryCacheMetrics,TestNameNodeRpcServer,TestNameNodeXAttr,TestPathComponents,TestSaveNamespace,TestSecondaryNameNodeUpgrade,TestSecondaryWebUi,TestSecureNameNodeWithExternalKdc,TestSecurityTokenEditLog,TestSnapshotPathINodes,TestStartup,TestStartupProgressServlet,TestStoragePolicySummary,TestStorageRestore,TestStreamFile


#sleep 5
#echo "methodTraceDump=true" > $SFIELD_INPUT

