#!/bin/sh

cd ..

# compile the code
ant jar
#ant jar-test

alljars=""
for jar in `ls lib/*.jar`; do
  alljars="$alljars:$jar"
done
for jar in `ls lib/jetty-ext/*.jar`; do
  alljars="$alljars:$jar"
done
for jar in `ls build/*.jar`; do
  alljars="$alljars:$jar"
done
#java -cp $alljars org.apache.hadoop.conf.Configuration
java -cp $alljars -Dlog4j.configuration="src/test/log4j.properties" junit.textui.TestRunner org.apache.hadoop.hdfs.TestDecommissionScale
