

MAX_NODE=128
HOSTNAME_PREFIX="node-"

YARN_RM="${HOSTNAME_PREFIX}0"
YARN_RM_IP=10.1.3.6
YARN_RM_HOSTNAME="${HOSTNAME_PREFIX}0"
HDFS_NN="${HOSTNAME_PREFIX}0"
HDFS_NN_IP=10.1.3.6
CLIENT_NODE="${HOSTNAME_PREFIX}0"
SLAVES_FILE="${HADOOP_CONF_DIR}/slaves"

#SLAVES_FILE=/proj/ucare/git/hadoop-ucare/psbin/mini-slaves

